version: '3.8'

services:
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - basic-network

  php:
    image: php:8.1-fpm
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - basic-network

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSOWORD: ${DB_PASSWORD}
    networks: 
      - basic-network
  
networks:
  basic-network:
    driver: bridge  