name: PHPCS

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPCS
        run: phpcs --standard=phpcs.xml .
      # - name: Detect coding standard violations
      #   run: vendor/bin/phpcs -q --report=checkstyle src